#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <time.h>

#define UP 8
#define DOWN 4
#define RESET 2
#define RESTART 1

unsigned char hexdigit[] = {0x3F, 0x06, 0x5B, 0x4F,
                            0x66, 0x6D, 0x7D, 0x07, 
                            0x7F, 0x6F, 0x77, 0x7C,
                            0x39, 0x5E, 0x79, 0x71};

int main() {
  srand(time(NULL));

  int i=0, j, k, l, disp2;
  long int ll, teste;
  int u,d,c,m;
  int sw = 0;
  int bt = 0;

  //variaveis do jooj
  int money = 50;
  int moneyDigits[2] = { 5, 0 };
  int bet = 0;
  int betDigits[2] = {0,0};
  int betted = 0;
  int won = 0;

  int dev = open("/dev/de2i150_altera", O_RDWR);

  printf("dev ID: %d\n", dev);

  while(1)
  {
    read(dev, &j, 0); //le switches

    sw = j & 0xFF;

    //printf("Switches: %d\n", sw);
    //printf("Botao: %d\n", bt);

    if(sw == 0)
    {
      //reseta premio ja que estamos apostando dnv
      won = 0;

      //isso garante que a aposta sera feita so uma vez0
      if(!betted){
        money -= bet;
        betted = 1;
      }


      u = rand()%10;
      d = rand()%10;
      c = rand()%10;
      m = rand()%10;
      
      i = 10;

      usleep(100000);

      k = hexdigit[u];
      k = k | hexdigit[d] << 8;
      k = k | hexdigit[c] << 16;
      k = k | hexdigit[m] << 24;
      k = ~k;

      while(i>0){
        write(dev, &k, 0);
        --i;
      }
      
      printf("Numero: %d%d%d%d\n", m,c,d,u);
    }

    if(sw == 1)
    {
      //reseta condiçao de apostas
      betted = 0;

      //CONFIGURAÇAO DE APOSTAS
      read(dev, &l, 1); //le bt
      bt = l & 0xFF;
      bt = abs(bt-15);

      moneyDigits[0] = money/10;
      moneyDigits[1] = money%10;

      betDigits[0] = bet/10;
      betDigits[1] = bet%10;


      disp2 = hexdigit[ betDigits[1] ];
      disp2 = disp2 | hexdigit[ betDigits[0] ] << 8;
      disp2 = disp2 | hexdigit[ moneyDigits[1] ] << 16;
      disp2 = disp2 | hexdigit[ moneyDigits[0] ] << 24;
      disp2 = ~disp2;

      write(dev, &disp2, 1);

      if (bt == UP)
        bet++;
      else if(bt == DOWN)
        bet--;
      else if(bt == RESET)
        bet = 0;
      else if(bt == RESTART){
        bet = 0;
        money = 50;
      }

      //impede de se apostar mais do que tem
      if(bet > money)
        bet = money;



      //PREMIAÇOES
      //se nao tiver ganho ainda, recebe o premio
      if(!won)
      {
        if(m == c && c == d && d == u) //4 numeros iguais
        {
          printf("JACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOTJACKPOT\n");
          
          money += bet<<4; //aposta * 8
        }
        else if( (m == c && c == d) || (c == d && d == u)) //3 numeros iguais
        {
          money += bet<<2; //aposta * 4
        }
        else if(m == c || c == d || d == u) //2 numeros iguais
        {
          money += bet<<1; //aposta * 2
        }

        won = 1;
      }

      usleep(200000);
    }

  }

  close(dev);
  return 0;
}
